### ISSUE TITLE
Duplicate of solido/awesome-flutter

### ISSUE THREAD

**Issue by aloisdeniel** [leisim/awesome-flutter-packages#1]
Hi,

Just wondering what's the purpose of this repository compared to [awesome-flutter](https://github.com/Solido/awesome-flutter) ?

I can't really understand the difference between the [components section](https://github.com/Solido/awesome-flutter#components) and this repository.

Following a unique source seems more useful to me than comparing two distinct ones.

**Comment by simc** [comment]
Hey,
I know of the other awesome list but I don't find it very useful for finding good packages.
There is no preview and just a very short description.
Also it is not very well structured.

I was looking for a flutter equivalent of https://github.com/wasabeef/awesome-android-ui but I didn't find one.

This is why I created this collection ;)

**Comment by simc** [comment]
If you have suggestions or questions, please create another issue...

**Comment by rrousselGit** [comment]
What about making a PR to `awesome-flutter` to improve the formatting then?

**Comment by simc** [comment]
@rrousselGit If you compare this repository with `awesome-flutter` you will notice that there are not much similarities.
There is no space for pictures or code samples in `awesome-flutter` how would a PR look like?

**Comment by aloisdeniel** [comment]
Maybe creating separate `.md` for each sections with more details if needed then. :)

**Comment by simc** [comment]
@aloisdeniel for this or for the other repository?
